version: '3.8'
services:
  public-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # Heroku-related environment variables
      ENVIRONMENT: production
      NODE_ENV: production
      PORT: 3000
      # Client URL
      CLIENT_URL: ${CLIENT_URL}
      # RabbitMQ (Heroku plugin)
      RABBIT_HOST: ${RABBIT_HOST}
      RABBIT_PORT: ${RABBIT_PORT}
      RABBIT_USERNAME: ${RABBIT_USERNAME}
      RABBIT_PASSWORD: ${RABBIT_PASSWORD}
      # Token configuration
      JWT_SECRET: ${JWT_SECRET}
      CLIENTS_JWT_SECRET: ${CLIENTS_JWT_SECRET}
      JWT_REFRESH_SECRET: ${JWT_REFRESH_SECRET}
      JWT_EXPIRATION_TIME: ${JWT_EXPIRATION_TIME}
      JWT_REFRESH_EXPIRATION_TIME: ${JWT_REFRESH_EXPIRATION_TIME}
      JWT_EXPIRATION_TIME_LONG: ${JWT_EXPIRATION_TIME_LONG}
    depends_on:
      - rabbitmq
  rabbitmq:
    image: rabbitmq:3-management
    hostname: rabbitmq
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_DEFAULT_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_DEFAULT_PASS}
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbit disk_free_limit 2147483648
    ports:
      - "5672:5672"
      - "15672:15672"
